//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCG.CoreApp.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCG.CoreApp.AppResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 560.
        /// </summary>
        public static string HeightLoginView {
            get {
                return ResourceManager.GetString("HeightLoginView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string HeightProductsView {
            get {
                return ResourceManager.GetString("HeightProductsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        public static string HeightUserSetupView {
            get {
                return ResourceManager.GetString("HeightUserSetupView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\Price_Manager.
        /// </summary>
        public static string PathIndesignDataFile {
            get {
                return ResourceManager.GetString("PathIndesignDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1272.
        /// </summary>
        public static string WidthLoginView {
            get {
                return ResourceManager.GetString("WidthLoginView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1370.
        /// </summary>
        public static string WidthProductsView {
            get {
                return ResourceManager.GetString("WidthProductsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1272.
        /// </summary>
        public static string WidthUserSetupView {
            get {
                return ResourceManager.GetString("WidthUserSetupView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowHeight.
        /// </summary>
        public static string WindowHeight {
            get {
                return ResourceManager.GetString("WindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowWidth.
        /// </summary>
        public static string WindowWidth {
            get {
                return ResourceManager.GetString("WindowWidth", resourceCulture);
            }
        }
    }
}
